---
title: "Lab 1"
author: "Kaicheng Luo"
date: "2019/9/9"
output:
  html_document: default
  pdf_document: default
---

Logistics:
GSI: Ryan Theisen
Office Hours: Wed 2-4pm Evans 444
email: theisen at berkeley.edu

```{r, include=FALSE}
library(knitr)
pca <- prcomp(USArrests, scale. = TRUE)
names(pca)
```

\section*{Problem 1}
PCA with EVD of correlation matrix
```{r}
# 1. Use scale() to standardize the USArrests data. Call this object arrests (matrix X)
arrests <- scale(USArrests)
# 2. Compute the sample correlation matrix R (don’t use cor()). Call this matrix R
R <- t(arrests) %*% arrests / (nrow(arrests) - 1)
# 3. Use the function eigen() to compute the Eigenvalue Decomposition of R.
eig <- eigen(R)
A <- diag(eig$values, nrow = 4)
V <- eig$vectors
# 4. Confirm that the matrix of loadings returned by prcomp() is equal to V
pca$rotation
V
# 5. Compute the product Z = XV and check that it’s equal to the principal components returned by prcomp(R)
Z <- arrests %*% V
# This shall return a zero matrix
Z - pca$x
```

\section*{Problem 2}
PCA with SVD of the data matrix
```{r}
# 1. Use the function svd() to compute the Singular Value Decomposition of arrests.
svd <- svd(arrests)
# 2. Take the output of svd() to create matrices U, D, V
D <- diag(svd$d, nrow = length(svd$d))
U <- svd$u
V <- svd$v
# 3. Compute the product Z = UD and check that it’s equal to the principal components returned by prcomp()
Z <- U %*% D
prcomp(arrests)$x
Z
# 4. Confirm that the matrix of loadings returned by prcomp() is equal to V
prcomp(arrests)$rotation
V
```

\section*{Problem 3}
PCA with EVD of association matrix
```{r, warning=FALSE}
asso <- arrests %*% t(arrests)
# Calculate the Eigen-Decomposotion of the Assosiation Matrix
eig2 <- eigen(asso)
A1 <- diag(eig2$values, nrow = length(eig2$values))
B <- eig2$vectors
for (i in 1:nrow(A1)){
  for (j in 1:ncol(A1)){
    A1[i,j] <- sqrt(A1[i,j])
  }
}
(B %*% A1)[,1:4]
pca$x
# Note that they're only different in terms of a flip of signs
```

