---
title: "Lab8"
author: "Kaicheng Luo"
date: "2019/11/4"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyr)
library(tidyverse)
library(dplyr)
library(car)
library(ISLR)
library(FactoMineR)
```

```{r}
data("Default")
yes <- Default %>%
  filter(default == 'Yes')
no <- Default %>%
  filter(default == 'No')
```

```{r}
# Exploratory Analysis
summary(yes)
summary(no)
ggplot() +
  geom_point(aes(x = income, y = balance, color = "No"), alpha = 0.5, data = no) + 
  geom_point(aes(x = income, y = balance, color = "Yes"), alpha = 0.5, data = yes)
ggplot() +
  geom_density(aes(x = balance, color = "Yes"), data = yes) +
  geom_density(aes(x = balance, color = "No"), data = no)
ggplot() +
  geom_density(aes(x = income, color = "Yes"), data = yes) +
  geom_density(aes(x = income, color = "No"), data = no)
```

```{r}
data <- Default %>%
  mutate(default = ifelse(default == "Yes", 1, 0))
result <- lm(default~balance, data = data)
ggplot() +
  geom_point(aes(x = balance, y = default), data = data) +
  geom_abline(aes(slope = result$coefficients[2], intercept = result$coefficients[1]), color = "maroon", size = 2)
```

```{r}
logreg_default <- glm(default ~ balance, family = binomial, data = Default)
summary(logreg_default)$coefficients
```

```{r}
predict(logreg_default, list(balance = seq(100,2000,100)), type = "response")
logreg_student <- glm(default ~ student, family = binomial, data = Default)
summary(logreg_student)$coefficients
```
Interpretation:
The indentity being a student, compared with a non-student, is associated with an increase in the log odds of default by 0.40 units.
```{r}
fullmodel <- glm(default~balance + student + income, data = Default, family = binomial)
summary(fullmodel)
# The regression coefficients on income is not significant. But all others (balance as student) are significant.
```

There's an apparent flip of sign because of multicolinearity. The independent variables are greatly correlated, leading to a very unstable estimation of our data.

```{r}
data("Smarket")
Smarket %>%
  select(-Direction) %>%
  cor()
PCA(Smarket[, -9], graph = T)
# The previous day returns are not so correlated to today's returns (Corr(Today, lag)<0.05)
ggplot() + theme_bw() +
  geom_point(aes(x = Year, y = Volume), data = Smarket)
```

```{r}
model <- glm(Direction ~ .-Today - Year, family = binomial, data = Smarket)
summary(model)
# None of the parameter seems significant (in terms of p-values)
# A unit's increase in yesterday's stock market price will lead to .07 percent decrease in logit of today's direction.
predict(model, type = "response") %>% head(10)
```

```{r}
check_convergence <- function(x,y,error = 1e-4){
  if (length(x)!=length(y)){
    print("Error: Diff in length")
    stop()
  }
  for (i in 1:length(x)){
    if (abs(x[i] - y[i]) > error){return(F)}
  }
  return(T)
}
b = rep(0, 7)
bnew = rep(0.1, 7)
X = cbind(1,as.matrix(Smarket %>% select(-Year, -Direction, -Today)))
y = as.matrix(Smarket %>% select(Direction) %>% mutate(Direction = ifelse(Direction == "Up", 1, 0)))
p = rep(0, nrow(X))
W = diag(1, nrow = nrow(X))
glm(y~X, family = binomial)
```

```{r}
while (check_convergence(b, bnew) == F){
  b = bnew
  for (i in 1:nrow(X)){
    p[i] = exp((X[i,]) %*% (b)) / (1 + exp((X[i,]) %*% (b)))
  }
  for (i in 1:nrow(X)){
    W[i,i] = p[i] * (1 - p[i])
  }
  z = X %*% b + solve(W) %*% (y-p)
  bnew = solve(t(X) %*% W %*% X) %*% t(X) %*% W %*% z
}
bnew
# Compare our results with those returned by the glm function:
round(bnew - model$coefficients, digits = 8)
```

```{r}
while (check_convergence(b, bnew) == F){
  b = bnew
  for (i in 1:nrow(X)){
    p[i] = exp((X[i,]) %*% (b)) / (1 + exp((X[i,]) %*% (b)))
  }
  Xt = X
  for (i in 1:nrow(X)){
    for (j in 1:ncol(X)){
      Xt[i,j] = X[i,j] * p[i] * (1 - p[i])
    }
  }
  bnew = b + solve(t(X) %*% Xt) %*% Xt %*% (y-p)
}
bnew
# Compare our results with those returned by the glm function:
round(bnew - model$coefficients, digits = 8)
```

